graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
  props:
    variables:
      editorTheme: "solarized light"
